package cn.enjoy.sys.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Department implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department_info.ID
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department_info.department_name
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	private String departmentName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department_info.parent_department
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	private String parentDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department_info.status
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department_info.department_code
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	private String departmentCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department_info.ID
	 * @return  the value of department_info.ID
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department_info.ID
	 * @param id  the value for department_info.ID
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}





	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department_info.department_name
	 * @return  the value of department_info.department_name
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department_info.department_name
	 * @param departmentName  the value for department_info.department_name
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName == null ? null : departmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department_info.parent_department
	 * @return  the value of department_info.parent_department
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public String getParentDepartment() {
		return parentDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department_info.parent_department
	 * @param parentDepartment  the value for department_info.parent_department
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public void setParentDepartment(String parentDepartment) {
		this.parentDepartment = parentDepartment == null ? null : parentDepartment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department_info.status
	 * @return  the value of department_info.status
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department_info.status
	 * @param status  the value for department_info.status
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department_info.department_code
	 * @return  the value of department_info.department_code
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public String getDepartmentCode() {
		return departmentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department_info.department_code
	 * @param departmentCode  the value for department_info.department_code
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode == null ? null : departmentCode.trim();
	}

}