package cn.enjoy.sys.model;

import java.util.Date;

public class KeyIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_identity.id
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_identity.key_code
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    private String keyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_identity.create_time
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_identity.code_index
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    private Long codeIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_identity.id
     *
     * @return the value of key_identity.id
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_identity.id
     *
     * @param id the value for key_identity.id
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_identity.key_code
     *
     * @return the value of key_identity.key_code
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public String getKeyCode() {
        return keyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_identity.key_code
     *
     * @param keyCode the value for key_identity.key_code
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public void setKeyCode(String keyCode) {
        this.keyCode = keyCode == null ? null : keyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_identity.create_time
     *
     * @return the value of key_identity.create_time
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_identity.create_time
     *
     * @param createTime the value for key_identity.create_time
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_identity.code_index
     *
     * @return the value of key_identity.code_index
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public Long getCodeIndex() {
        return codeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_identity.code_index
     *
     * @param codeIndex the value for key_identity.code_index
     *
     * @mbggenerated Tue Aug 22 16:22:04 CST 2017
     */
    public void setCodeIndex(Long codeIndex) {
        this.codeIndex = codeIndex;
    }
}