package cn.enjoy.sys.model;

import java.io.Serializable;

public class Oauth2Client implements Serializable{
    private static final long serialVersionUID = -8266007612414005822L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oauth2_client.id
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oauth2_client.client_name
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oauth2_client.client_id
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oauth2_client.client_secret
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    private String clientSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oauth2_client.logout_url
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    private String logoutUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oauth2_client.id
     *
     * @return the value of sys_oauth2_client.id
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oauth2_client.id
     *
     * @param id the value for sys_oauth2_client.id
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oauth2_client.client_name
     *
     * @return the value of sys_oauth2_client.client_name
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oauth2_client.client_name
     *
     * @param clientName the value for sys_oauth2_client.client_name
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oauth2_client.client_id
     *
     * @return the value of sys_oauth2_client.client_id
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oauth2_client.client_id
     *
     * @param clientId the value for sys_oauth2_client.client_id
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oauth2_client.client_secret
     *
     * @return the value of sys_oauth2_client.client_secret
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oauth2_client.client_secret
     *
     * @param clientSecret the value for sys_oauth2_client.client_secret
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oauth2_client.logout_url
     *
     * @return the value of sys_oauth2_client.logout_url
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public String getLogoutUrl() {
        return logoutUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oauth2_client.logout_url
     *
     * @param logoutUrl the value for sys_oauth2_client.logout_url
     *
     * @mbg.generated Mon Apr 02 15:19:11 CST 2018
     */
    public void setLogoutUrl(String logoutUrl) {
        this.logoutUrl = logoutUrl == null ? null : logoutUrl.trim();
    }
}