package cn.enjoy.sys.model;

import java.io.Serializable;

public class SysDictType implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_type.id
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_type.type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_type.name
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_type.valid
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	private Integer valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_type.description
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_type.id
	 * @return  the value of sys_dict_type.id
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_type.id
	 * @param id  the value for sys_dict_type.id
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_type.type
	 * @return  the value of sys_dict_type.type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_type.type
	 * @param type  the value for sys_dict_type.type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_type.name
	 * @return  the value of sys_dict_type.name
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_type.name
	 * @param name  the value for sys_dict_type.name
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_type.valid
	 * @return  the value of sys_dict_type.valid
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public Integer getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_type.valid
	 * @param valid  the value for sys_dict_type.valid
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public void setValid(Integer valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_type.description
	 * @return  the value of sys_dict_type.description
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_type.description
	 * @param description  the value for sys_dict_type.description
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}