package cn.enjoy.sys.model;

import java.util.Date;

public class SysEmployee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.id
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.user_id
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.join_date
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    private Date joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.create_time
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.create_user
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.update_time
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.update_user
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.id
     *
     * @return the value of sys_employee.id
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.id
     *
     * @param id the value for sys_employee.id
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.user_id
     *
     * @return the value of sys_employee.user_id
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.user_id
     *
     * @param userId the value for sys_employee.user_id
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.join_date
     *
     * @return the value of sys_employee.join_date
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.join_date
     *
     * @param joinDate the value for sys_employee.join_date
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.create_time
     *
     * @return the value of sys_employee.create_time
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.create_time
     *
     * @param createTime the value for sys_employee.create_time
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.create_user
     *
     * @return the value of sys_employee.create_user
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.create_user
     *
     * @param createUser the value for sys_employee.create_user
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.update_time
     *
     * @return the value of sys_employee.update_time
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.update_time
     *
     * @param updateTime the value for sys_employee.update_time
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.update_user
     *
     * @return the value of sys_employee.update_user
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.update_user
     *
     * @param updateUser the value for sys_employee.update_user
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}