package cn.enjoy.sys.model;

import java.util.Date;
import java.util.List;

public class SysOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.id
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.name
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.desc
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.create_time
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.create_user
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.update_user
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.update_time
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.id
     *
     * @return the value of sys_organization.id
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.id
     *
     * @param id the value for sys_organization.id
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.name
     *
     * @return the value of sys_organization.name
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.name
     *
     * @param name the value for sys_organization.name
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.desc
     *
     * @return the value of sys_organization.desc
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.desc
     *
     * @param desc the value for sys_organization.desc
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.create_time
     *
     * @return the value of sys_organization.create_time
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.create_time
     *
     * @param createTime the value for sys_organization.create_time
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.create_user
     *
     * @return the value of sys_organization.create_user
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.create_user
     *
     * @param createUser the value for sys_organization.create_user
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.update_user
     *
     * @return the value of sys_organization.update_user
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.update_user
     *
     * @param updateUser the value for sys_organization.update_user
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.update_time
     *
     * @return the value of sys_organization.update_time
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.update_time
     *
     * @param updateTime the value for sys_organization.update_time
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }



     List<SysUserOrganization> users;
    public List<SysUserOrganization> getUsers() {
        return users;
    }

    public void setUsers(List<SysUserOrganization> users) {
        this.users = users;
    }


   private  String members;
    public String getMembers() {
        return members;
    }

    public void setMembers(String members) {
        this.members = members;
    }



}