package cn.enjoy.sys.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class SysParam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.id
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.code
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.value
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.is_valid
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.description
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.update_time
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.id
     *
     * @return the value of sys_param.id
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.id
     *
     * @param id the value for sys_param.id
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.code
     *
     * @return the value of sys_param.code
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.code
     *
     * @param code the value for sys_param.code
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.value
     *
     * @return the value of sys_param.value
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.value
     *
     * @param value the value for sys_param.value
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.is_valid
     *
     * @return the value of sys_param.is_valid
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.is_valid
     *
     * @param isValid the value for sys_param.is_valid
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.description
     *
     * @return the value of sys_param.description
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.description
     *
     * @param description the value for sys_param.description
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.update_time
     *
     * @return the value of sys_param.update_time
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.update_time
     *
     * @param updateTime the value for sys_param.update_time
     *
     * @mbggenerated Tue Oct 31 09:13:55 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}