package cn.enjoy.sys.model;

public class SysUserBind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_bind.id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_bind.type
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_bind.auth_id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    private String authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_bind.status
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_bind.bind_user_id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    private String bindUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_bind.user_name
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_bind.remark
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_bind.id
     *
     * @return the value of sys_user_bind.id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_bind.id
     *
     * @param id the value for sys_user_bind.id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_bind.type
     *
     * @return the value of sys_user_bind.type
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_bind.type
     *
     * @param type the value for sys_user_bind.type
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_bind.auth_id
     *
     * @return the value of sys_user_bind.auth_id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_bind.auth_id
     *
     * @param authId the value for sys_user_bind.auth_id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_bind.status
     *
     * @return the value of sys_user_bind.status
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_bind.status
     *
     * @param status the value for sys_user_bind.status
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_bind.bind_user_id
     *
     * @return the value of sys_user_bind.bind_user_id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public String getBindUserId() {
        return bindUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_bind.bind_user_id
     *
     * @param bindUserId the value for sys_user_bind.bind_user_id
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public void setBindUserId(String bindUserId) {
        this.bindUserId = bindUserId == null ? null : bindUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_bind.user_name
     *
     * @return the value of sys_user_bind.user_name
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_bind.user_name
     *
     * @param userName the value for sys_user_bind.user_name
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_bind.remark
     *
     * @return the value of sys_user_bind.remark
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_bind.remark
     *
     * @param remark the value for sys_user_bind.remark
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}