package cn.enjoy.sys.model;

import java.util.Date;

public class SysUserOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.user_id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.organization_id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.supervise
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private Byte supervise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.create_time
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.create_user
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.update_user
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_organization.update_time
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.id
     *
     * @return the value of sys_user_organization.id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.id
     *
     * @param id the value for sys_user_organization.id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.user_id
     *
     * @return the value of sys_user_organization.user_id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.user_id
     *
     * @param userId the value for sys_user_organization.user_id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.organization_id
     *
     * @return the value of sys_user_organization.organization_id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.organization_id
     *
     * @param organizationId the value for sys_user_organization.organization_id
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.supervise
     *
     * @return the value of sys_user_organization.supervise
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public Byte getSupervise() {
        return supervise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.supervise
     *
     * @param supervise the value for sys_user_organization.supervise
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setSupervise(Byte supervise) {
        this.supervise = supervise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.create_time
     *
     * @return the value of sys_user_organization.create_time
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.create_time
     *
     * @param createTime the value for sys_user_organization.create_time
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.create_user
     *
     * @return the value of sys_user_organization.create_user
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.create_user
     *
     * @param createUser the value for sys_user_organization.create_user
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.update_user
     *
     * @return the value of sys_user_organization.update_user
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.update_user
     *
     * @param updateUser the value for sys_user_organization.update_user
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_organization.update_time
     *
     * @return the value of sys_user_organization.update_time
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_organization.update_time
     *
     * @param updateTime the value for sys_user_organization.update_time
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public SysUser getUser() {
        return user;
    }

    public void setUser(SysUser user) {
        this.user = user;
    }

    private SysUser user;
}