package cn.enjoy.sys.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toroot_user.id
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toroot_user.username
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toroot_user.passwd
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toroot_user.id
     *
     * @return the value of toroot_user.id
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toroot_user.id
     *
     * @param id the value for toroot_user.id
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toroot_user.username
     *
     * @return the value of toroot_user.username
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toroot_user.username
     *
     * @param username the value for toroot_user.username
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toroot_user.passwd
     *
     * @return the value of toroot_user.passwd
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toroot_user.passwd
     *
     * @param passwd the value for toroot_user.passwd
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }
}