package cn.enjoy.sys.model;

import java.util.Date;

public class UserDepartmentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_department_info.id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_department_info.user_id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_department_info.department_id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_department_info.position_level
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    private String positionLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_department_info.create_user
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_department_info.create_time
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_department_info.id
     *
     * @return the value of user_department_info.id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_department_info.id
     *
     * @param id the value for user_department_info.id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_department_info.user_id
     *
     * @return the value of user_department_info.user_id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_department_info.user_id
     *
     * @param userId the value for user_department_info.user_id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_department_info.department_id
     *
     * @return the value of user_department_info.department_id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_department_info.department_id
     *
     * @param departmentId the value for user_department_info.department_id
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_department_info.position_level
     *
     * @return the value of user_department_info.position_level
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public String getPositionLevel() {
        return positionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_department_info.position_level
     *
     * @param positionLevel the value for user_department_info.position_level
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public void setPositionLevel(String positionLevel) {
        this.positionLevel = positionLevel == null ? null : positionLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_department_info.create_user
     *
     * @return the value of user_department_info.create_user
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_department_info.create_user
     *
     * @param createUser the value for user_department_info.create_user
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_department_info.create_time
     *
     * @return the value of user_department_info.create_time
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_department_info.create_time
     *
     * @param createTime the value for user_department_info.create_time
     *
     * @mbggenerated Tue Apr 25 16:38:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}