package cn.enjoy.mall.model;

import java.io.Serializable;

public class GoodsType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_type.id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_type.name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_type.id
     *
     * @return the value of tp_goods_type.id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_type.id
     *
     * @param id the value for tp_goods_type.id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_type.name
     *
     * @return the value of tp_goods_type.name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_type.name
     *
     * @param name the value for tp_goods_type.name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}