package cn.enjoy.mall.model;

import java.io.Serializable;

public class GoodsAttribute implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer attrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.attr_name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.type_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.attr_index
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Byte attrIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.attr_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Byte attrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.attr_input_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Byte attrInputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.order
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Byte order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attribute.attr_values
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String attrValues;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.attr_id
     *
     * @return the value of tp_goods_attribute.attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.attr_id
     *
     * @param attrId the value for tp_goods_attribute.attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.attr_name
     *
     * @return the value of tp_goods_attribute.attr_name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.attr_name
     *
     * @param attrName the value for tp_goods_attribute.attr_name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.type_id
     *
     * @return the value of tp_goods_attribute.type_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.type_id
     *
     * @param typeId the value for tp_goods_attribute.type_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setTypeId(Short typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.attr_index
     *
     * @return the value of tp_goods_attribute.attr_index
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Byte getAttrIndex() {
        return attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.attr_index
     *
     * @param attrIndex the value for tp_goods_attribute.attr_index
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrIndex(Byte attrIndex) {
        this.attrIndex = attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.attr_type
     *
     * @return the value of tp_goods_attribute.attr_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Byte getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.attr_type
     *
     * @param attrType the value for tp_goods_attribute.attr_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrType(Byte attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.attr_input_type
     *
     * @return the value of tp_goods_attribute.attr_input_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Byte getAttrInputType() {
        return attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.attr_input_type
     *
     * @param attrInputType the value for tp_goods_attribute.attr_input_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrInputType(Byte attrInputType) {
        this.attrInputType = attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.order
     *
     * @return the value of tp_goods_attribute.order
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Byte getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.order
     *
     * @param order the value for tp_goods_attribute.order
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setOrder(Byte order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attribute.attr_values
     *
     * @return the value of tp_goods_attribute.attr_values
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getAttrValues() {
        return attrValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attribute.attr_values
     *
     * @param attrValues the value for tp_goods_attribute.attr_values
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrValues(String attrValues) {
        this.attrValues = attrValues == null ? null : attrValues.trim();
    }
}