package cn.enjoy.mall.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Goods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.goods_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.cat_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.extend_cat_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer extendCatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.goods_sn
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.goods_name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.click_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer clickCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.brand_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.store_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short storeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.comment_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.weight
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.market_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.shop_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private BigDecimal shopPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.cost_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.keywords
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.goods_remark
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String goodsRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.original_img
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String originalImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.is_real
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Boolean isReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.is_on_sale
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Boolean isOnSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.is_free_shipping
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Boolean isFreeShipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.on_time
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer onTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.sort
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.is_recommend
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Boolean isRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.is_new
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Boolean isNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.is_hot
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Boolean isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.last_update
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.spec_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short specType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.give_integral
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer giveIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.exchange_integral
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer exchangeIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.suppliers_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short suppliersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.sales_sum
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer salesSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.prom_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Boolean promType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.prom_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer promId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.commission
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.spu
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String spu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.sku
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.shipping_area_ids
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String shippingAreaIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods.goods_content
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String goodsContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.goods_id
     *
     * @return the value of tp_goods.goods_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.goods_id
     *
     * @param goodsId the value for tp_goods.goods_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.cat_id
     *
     * @return the value of tp_goods.cat_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.cat_id
     *
     * @param catId the value for tp_goods.cat_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.extend_cat_id
     *
     * @return the value of tp_goods.extend_cat_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getExtendCatId() {
        return extendCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.extend_cat_id
     *
     * @param extendCatId the value for tp_goods.extend_cat_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setExtendCatId(Integer extendCatId) {
        this.extendCatId = extendCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.goods_sn
     *
     * @return the value of tp_goods.goods_sn
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.goods_sn
     *
     * @param goodsSn the value for tp_goods.goods_sn
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.goods_name
     *
     * @return the value of tp_goods.goods_name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.goods_name
     *
     * @param goodsName the value for tp_goods.goods_name
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.click_count
     *
     * @return the value of tp_goods.click_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.click_count
     *
     * @param clickCount the value for tp_goods.click_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.brand_id
     *
     * @return the value of tp_goods.brand_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.brand_id
     *
     * @param brandId the value for tp_goods.brand_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setBrandId(Short brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.store_count
     *
     * @return the value of tp_goods.store_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getStoreCount() {
        return storeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.store_count
     *
     * @param storeCount the value for tp_goods.store_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setStoreCount(Short storeCount) {
        this.storeCount = storeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.comment_count
     *
     * @return the value of tp_goods.comment_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.comment_count
     *
     * @param commentCount the value for tp_goods.comment_count
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setCommentCount(Short commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.weight
     *
     * @return the value of tp_goods.weight
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.weight
     *
     * @param weight the value for tp_goods.weight
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.market_price
     *
     * @return the value of tp_goods.market_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.market_price
     *
     * @param marketPrice the value for tp_goods.market_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.shop_price
     *
     * @return the value of tp_goods.shop_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public BigDecimal getShopPrice() {
        return shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.shop_price
     *
     * @param shopPrice the value for tp_goods.shop_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setShopPrice(BigDecimal shopPrice) {
        this.shopPrice = shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.cost_price
     *
     * @return the value of tp_goods.cost_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.cost_price
     *
     * @param costPrice the value for tp_goods.cost_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.keywords
     *
     * @return the value of tp_goods.keywords
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.keywords
     *
     * @param keywords the value for tp_goods.keywords
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.goods_remark
     *
     * @return the value of tp_goods.goods_remark
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getGoodsRemark() {
        return goodsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.goods_remark
     *
     * @param goodsRemark the value for tp_goods.goods_remark
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsRemark(String goodsRemark) {
        this.goodsRemark = goodsRemark == null ? null : goodsRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.original_img
     *
     * @return the value of tp_goods.original_img
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getOriginalImg() {
        return originalImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.original_img
     *
     * @param originalImg the value for tp_goods.original_img
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setOriginalImg(String originalImg) {
        this.originalImg = originalImg == null ? null : originalImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.is_real
     *
     * @return the value of tp_goods.is_real
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Boolean getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.is_real
     *
     * @param isReal the value for tp_goods.is_real
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setIsReal(Boolean isReal) {
        this.isReal = isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.is_on_sale
     *
     * @return the value of tp_goods.is_on_sale
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Boolean getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.is_on_sale
     *
     * @param isOnSale the value for tp_goods.is_on_sale
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setIsOnSale(Boolean isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.is_free_shipping
     *
     * @return the value of tp_goods.is_free_shipping
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Boolean getIsFreeShipping() {
        return isFreeShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.is_free_shipping
     *
     * @param isFreeShipping the value for tp_goods.is_free_shipping
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setIsFreeShipping(Boolean isFreeShipping) {
        this.isFreeShipping = isFreeShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.on_time
     *
     * @return the value of tp_goods.on_time
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getOnTime() {
        return onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.on_time
     *
     * @param onTime the value for tp_goods.on_time
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setOnTime(Integer onTime) {
        this.onTime = onTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.sort
     *
     * @return the value of tp_goods.sort
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.sort
     *
     * @param sort the value for tp_goods.sort
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.is_recommend
     *
     * @return the value of tp_goods.is_recommend
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Boolean getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.is_recommend
     *
     * @param isRecommend the value for tp_goods.is_recommend
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setIsRecommend(Boolean isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.is_new
     *
     * @return the value of tp_goods.is_new
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.is_new
     *
     * @param isNew the value for tp_goods.is_new
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.is_hot
     *
     * @return the value of tp_goods.is_hot
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.is_hot
     *
     * @param isHot the value for tp_goods.is_hot
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.last_update
     *
     * @return the value of tp_goods.last_update
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.last_update
     *
     * @param lastUpdate the value for tp_goods.last_update
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setLastUpdate(Integer lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.goods_type
     *
     * @return the value of tp_goods.goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.goods_type
     *
     * @param goodsType the value for tp_goods.goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsType(Short goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.spec_type
     *
     * @return the value of tp_goods.spec_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getSpecType() {
        return specType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.spec_type
     *
     * @param specType the value for tp_goods.spec_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setSpecType(Short specType) {
        this.specType = specType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.give_integral
     *
     * @return the value of tp_goods.give_integral
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getGiveIntegral() {
        return giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.give_integral
     *
     * @param giveIntegral the value for tp_goods.give_integral
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGiveIntegral(Integer giveIntegral) {
        this.giveIntegral = giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.exchange_integral
     *
     * @return the value of tp_goods.exchange_integral
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getExchangeIntegral() {
        return exchangeIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.exchange_integral
     *
     * @param exchangeIntegral the value for tp_goods.exchange_integral
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setExchangeIntegral(Integer exchangeIntegral) {
        this.exchangeIntegral = exchangeIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.suppliers_id
     *
     * @return the value of tp_goods.suppliers_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getSuppliersId() {
        return suppliersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.suppliers_id
     *
     * @param suppliersId the value for tp_goods.suppliers_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setSuppliersId(Short suppliersId) {
        this.suppliersId = suppliersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.sales_sum
     *
     * @return the value of tp_goods.sales_sum
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getSalesSum() {
        return salesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.sales_sum
     *
     * @param salesSum the value for tp_goods.sales_sum
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setSalesSum(Integer salesSum) {
        this.salesSum = salesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.prom_type
     *
     * @return the value of tp_goods.prom_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Boolean getPromType() {
        return promType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.prom_type
     *
     * @param promType the value for tp_goods.prom_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setPromType(Boolean promType) {
        this.promType = promType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.prom_id
     *
     * @return the value of tp_goods.prom_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getPromId() {
        return promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.prom_id
     *
     * @param promId the value for tp_goods.prom_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setPromId(Integer promId) {
        this.promId = promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.commission
     *
     * @return the value of tp_goods.commission
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.commission
     *
     * @param commission the value for tp_goods.commission
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.spu
     *
     * @return the value of tp_goods.spu
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getSpu() {
        return spu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.spu
     *
     * @param spu the value for tp_goods.spu
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setSpu(String spu) {
        this.spu = spu == null ? null : spu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.sku
     *
     * @return the value of tp_goods.sku
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.sku
     *
     * @param sku the value for tp_goods.sku
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.shipping_area_ids
     *
     * @return the value of tp_goods.shipping_area_ids
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getShippingAreaIds() {
        return shippingAreaIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.shipping_area_ids
     *
     * @param shippingAreaIds the value for tp_goods.shipping_area_ids
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setShippingAreaIds(String shippingAreaIds) {
        this.shippingAreaIds = shippingAreaIds == null ? null : shippingAreaIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods.goods_content
     *
     * @return the value of tp_goods.goods_content
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getGoodsContent() {
        return goodsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods.goods_content
     *
     * @param goodsContent the value for tp_goods.goods_content
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsContent(String goodsContent) {
        this.goodsContent = goodsContent == null ? null : goodsContent.trim();
    }

    private String catName;//分类名称

    public String getCatName() {
        return catName;
    }

    public void setCatName(String catName) {
        this.catName = catName;
    }

    private String catParentIdPath;//分类 家族图谱

    public String getCatParentIdPath() {
        return catParentIdPath;
    }

    public void setCatParentIdPath(String catParentIdPath) {
        this.catParentIdPath = catParentIdPath;
    }
}