package cn.enjoy.mall.model;

import java.io.Serializable;

public class GoodsAttr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attr.goods_attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer goodsAttrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attr.goods_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attr.attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Short attrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attr.attr_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String attrPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_attr.attr_value
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String attrValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attr.goods_attr_id
     *
     * @return the value of tp_goods_attr.goods_attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attr.goods_attr_id
     *
     * @param goodsAttrId the value for tp_goods_attr.goods_attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsAttrId(Integer goodsAttrId) {
        this.goodsAttrId = goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attr.goods_id
     *
     * @return the value of tp_goods_attr.goods_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attr.goods_id
     *
     * @param goodsId the value for tp_goods_attr.goods_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attr.attr_id
     *
     * @return the value of tp_goods_attr.attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Short getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attr.attr_id
     *
     * @param attrId the value for tp_goods_attr.attr_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrId(Short attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attr.attr_price
     *
     * @return the value of tp_goods_attr.attr_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getAttrPrice() {
        return attrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attr.attr_price
     *
     * @param attrPrice the value for tp_goods_attr.attr_price
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrPrice(String attrPrice) {
        this.attrPrice = attrPrice == null ? null : attrPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_attr.attr_value
     *
     * @return the value of tp_goods_attr.attr_value
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_attr.attr_value
     *
     * @param attrValue the value for tp_goods_attr.attr_value
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    private String attrName;//属性名称

    public String getAttrName() {
        return attrName;
    }

    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }
}