package cn.enjoy.mall.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class GoodsCategory implements Serializable {
    private static final long serialVersionUID = -1598312944643324328L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.id
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.name
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.mobile_name
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private String mobileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.parent_id
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.parent_id_path
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private String parentIdPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.level
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Short level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.sort_order
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Short sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.is_show
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.image
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.is_hot
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Boolean isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.cat_group
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Boolean catGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_goods_category.commission_rate
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    private Boolean commissionRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.id
     *
     * @return the value of tp_goods_category.id
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.id
     *
     * @param id the value for tp_goods_category.id
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.name
     *
     * @return the value of tp_goods_category.name
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.name
     *
     * @param name the value for tp_goods_category.name
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.mobile_name
     *
     * @return the value of tp_goods_category.mobile_name
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public String getMobileName() {
        return mobileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.mobile_name
     *
     * @param mobileName the value for tp_goods_category.mobile_name
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setMobileName(String mobileName) {
        this.mobileName = mobileName == null ? null : mobileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.parent_id
     *
     * @return the value of tp_goods_category.parent_id
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.parent_id
     *
     * @param parentId the value for tp_goods_category.parent_id
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.parent_id_path
     *
     * @return the value of tp_goods_category.parent_id_path
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public String getParentIdPath() {
        return parentIdPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.parent_id_path
     *
     * @param parentIdPath the value for tp_goods_category.parent_id_path
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setParentIdPath(String parentIdPath) {
        this.parentIdPath = parentIdPath == null ? null : parentIdPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.level
     *
     * @return the value of tp_goods_category.level
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.level
     *
     * @param level the value for tp_goods_category.level
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.sort_order
     *
     * @return the value of tp_goods_category.sort_order
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Short getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.sort_order
     *
     * @param sortOrder the value for tp_goods_category.sort_order
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setSortOrder(Short sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.is_show
     *
     * @return the value of tp_goods_category.is_show
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.is_show
     *
     * @param isShow the value for tp_goods_category.is_show
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.image
     *
     * @return the value of tp_goods_category.image
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.image
     *
     * @param image the value for tp_goods_category.image
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.is_hot
     *
     * @return the value of tp_goods_category.is_hot
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.is_hot
     *
     * @param isHot the value for tp_goods_category.is_hot
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.cat_group
     *
     * @return the value of tp_goods_category.cat_group
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Boolean getCatGroup() {
        return catGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.cat_group
     *
     * @param catGroup the value for tp_goods_category.cat_group
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setCatGroup(Boolean catGroup) {
        this.catGroup = catGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_goods_category.commission_rate
     *
     * @return the value of tp_goods_category.commission_rate
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public Boolean getCommissionRate() {
        return commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_goods_category.commission_rate
     *
     * @param commissionRate the value for tp_goods_category.commission_rate
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    public void setCommissionRate(Boolean commissionRate) {
        this.commissionRate = commissionRate;
    }
}