package cn.enjoy.mall.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrderGoods implements Serializable{
    private static final long serialVersionUID = -2308724367849458098L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.rec_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Integer recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.order_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.spec_goods_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Integer specGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.goods_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.goods_name
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.goods_sn
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.goods_num
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Short goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.market_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.goods_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.cost_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.member_goods_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private BigDecimal memberGoodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.give_integral
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Integer giveIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.spec_key
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private String specKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.spec_key_name
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private String specKeyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.bar_code
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.is_comment
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Boolean isComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.prom_type
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Boolean promType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.prom_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Integer promId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.is_send
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Boolean isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.delivery_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private Integer deliveryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.sku
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_goods.original_img
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    private String originalImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.rec_id
     *
     * @return the value of tp_order_goods.rec_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.rec_id
     *
     * @param recId the value for tp_order_goods.rec_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.order_id
     *
     * @return the value of tp_order_goods.order_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.order_id
     *
     * @param orderId the value for tp_order_goods.order_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.spec_goods_id
     *
     * @return the value of tp_order_goods.spec_goods_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Integer getSpecGoodsId() {
        return specGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.spec_goods_id
     *
     * @param specGoodsId the value for tp_order_goods.spec_goods_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setSpecGoodsId(Integer specGoodsId) {
        this.specGoodsId = specGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.goods_id
     *
     * @return the value of tp_order_goods.goods_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.goods_id
     *
     * @param goodsId the value for tp_order_goods.goods_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.goods_name
     *
     * @return the value of tp_order_goods.goods_name
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.goods_name
     *
     * @param goodsName the value for tp_order_goods.goods_name
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.goods_sn
     *
     * @return the value of tp_order_goods.goods_sn
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.goods_sn
     *
     * @param goodsSn the value for tp_order_goods.goods_sn
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.goods_num
     *
     * @return the value of tp_order_goods.goods_num
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Short getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.goods_num
     *
     * @param goodsNum the value for tp_order_goods.goods_num
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setGoodsNum(Short goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.market_price
     *
     * @return the value of tp_order_goods.market_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.market_price
     *
     * @param marketPrice the value for tp_order_goods.market_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.goods_price
     *
     * @return the value of tp_order_goods.goods_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.goods_price
     *
     * @param goodsPrice the value for tp_order_goods.goods_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.cost_price
     *
     * @return the value of tp_order_goods.cost_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.cost_price
     *
     * @param costPrice the value for tp_order_goods.cost_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.member_goods_price
     *
     * @return the value of tp_order_goods.member_goods_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public BigDecimal getMemberGoodsPrice() {
        return memberGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.member_goods_price
     *
     * @param memberGoodsPrice the value for tp_order_goods.member_goods_price
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setMemberGoodsPrice(BigDecimal memberGoodsPrice) {
        this.memberGoodsPrice = memberGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.give_integral
     *
     * @return the value of tp_order_goods.give_integral
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Integer getGiveIntegral() {
        return giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.give_integral
     *
     * @param giveIntegral the value for tp_order_goods.give_integral
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setGiveIntegral(Integer giveIntegral) {
        this.giveIntegral = giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.spec_key
     *
     * @return the value of tp_order_goods.spec_key
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public String getSpecKey() {
        return specKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.spec_key
     *
     * @param specKey the value for tp_order_goods.spec_key
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setSpecKey(String specKey) {
        this.specKey = specKey == null ? null : specKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.spec_key_name
     *
     * @return the value of tp_order_goods.spec_key_name
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public String getSpecKeyName() {
        return specKeyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.spec_key_name
     *
     * @param specKeyName the value for tp_order_goods.spec_key_name
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setSpecKeyName(String specKeyName) {
        this.specKeyName = specKeyName == null ? null : specKeyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.bar_code
     *
     * @return the value of tp_order_goods.bar_code
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.bar_code
     *
     * @param barCode the value for tp_order_goods.bar_code
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.is_comment
     *
     * @return the value of tp_order_goods.is_comment
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Boolean getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.is_comment
     *
     * @param isComment the value for tp_order_goods.is_comment
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setIsComment(Boolean isComment) {
        this.isComment = isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.prom_type
     *
     * @return the value of tp_order_goods.prom_type
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Boolean getPromType() {
        return promType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.prom_type
     *
     * @param promType the value for tp_order_goods.prom_type
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setPromType(Boolean promType) {
        this.promType = promType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.prom_id
     *
     * @return the value of tp_order_goods.prom_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Integer getPromId() {
        return promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.prom_id
     *
     * @param promId the value for tp_order_goods.prom_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setPromId(Integer promId) {
        this.promId = promId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.is_send
     *
     * @return the value of tp_order_goods.is_send
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Boolean getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.is_send
     *
     * @param isSend the value for tp_order_goods.is_send
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setIsSend(Boolean isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.delivery_id
     *
     * @return the value of tp_order_goods.delivery_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.delivery_id
     *
     * @param deliveryId the value for tp_order_goods.delivery_id
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.sku
     *
     * @return the value of tp_order_goods.sku
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.sku
     *
     * @param sku the value for tp_order_goods.sku
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_goods.original_img
     *
     * @return the value of tp_order_goods.original_img
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public String getOriginalImg() {
        return originalImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_goods.original_img
     *
     * @param originalImg the value for tp_order_goods.original_img
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    public void setOriginalImg(String originalImg) {
        this.originalImg = originalImg == null ? null : originalImg.trim();
    }
}