package cn.enjoy.mall.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

public class Order implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_sn
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.user_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.shipping_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Integer shippingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.pay_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.consignee
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.area
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.address
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.zipcode
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.mobile
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.email
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.shipping_code
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String shippingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.shipping_name
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String shippingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.pay_code
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.pay_name
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.invoice_title
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.goods_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.shipping_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal shippingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.user_money
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal userMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.coupon_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal couponPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.integral
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.integral_money
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal integralMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.total_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.add_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Long addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.shipping_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Long shippingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.confirm_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Long confirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.pay_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Long payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_prom_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Short orderPromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.order_prom_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal orderPromAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.discount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.user_note
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String userNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.admin_note
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String adminNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.parent_sn
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private String parentSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.is_distribut
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Boolean isDistribut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.receive_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    private Long receiveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_id
     *
     * @return the value of tp_order.order_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_id
     *
     * @param orderId the value for tp_order.order_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_sn
     *
     * @return the value of tp_order.order_sn
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_sn
     *
     * @param orderSn the value for tp_order.order_sn
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.user_id
     *
     * @return the value of tp_order.user_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.user_id
     *
     * @param userId the value for tp_order.user_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_status
     *
     * @return the value of tp_order.order_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_status
     *
     * @param orderStatus the value for tp_order.order_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.shipping_status
     *
     * @return the value of tp_order.shipping_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Integer getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.shipping_status
     *
     * @param shippingStatus the value for tp_order.shipping_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setShippingStatus(Integer shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.pay_status
     *
     * @return the value of tp_order.pay_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.pay_status
     *
     * @param payStatus the value for tp_order.pay_status
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.consignee
     *
     * @return the value of tp_order.consignee
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.consignee
     *
     * @param consignee the value for tp_order.consignee
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.area
     *
     * @return the value of tp_order.area
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.area
     *
     * @param area the value for tp_order.area
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.address
     *
     * @return the value of tp_order.address
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.address
     *
     * @param address the value for tp_order.address
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.zipcode
     *
     * @return the value of tp_order.zipcode
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.zipcode
     *
     * @param zipcode the value for tp_order.zipcode
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.mobile
     *
     * @return the value of tp_order.mobile
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.mobile
     *
     * @param mobile the value for tp_order.mobile
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.email
     *
     * @return the value of tp_order.email
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.email
     *
     * @param email the value for tp_order.email
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.shipping_code
     *
     * @return the value of tp_order.shipping_code
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getShippingCode() {
        return shippingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.shipping_code
     *
     * @param shippingCode the value for tp_order.shipping_code
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setShippingCode(String shippingCode) {
        this.shippingCode = shippingCode == null ? null : shippingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.shipping_name
     *
     * @return the value of tp_order.shipping_name
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.shipping_name
     *
     * @param shippingName the value for tp_order.shipping_name
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.pay_code
     *
     * @return the value of tp_order.pay_code
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.pay_code
     *
     * @param payCode the value for tp_order.pay_code
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.pay_name
     *
     * @return the value of tp_order.pay_name
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.pay_name
     *
     * @param payName the value for tp_order.pay_name
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.invoice_title
     *
     * @return the value of tp_order.invoice_title
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.invoice_title
     *
     * @param invoiceTitle the value for tp_order.invoice_title
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.goods_price
     *
     * @return the value of tp_order.goods_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.goods_price
     *
     * @param goodsPrice the value for tp_order.goods_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.shipping_price
     *
     * @return the value of tp_order.shipping_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getShippingPrice() {
        return shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.shipping_price
     *
     * @param shippingPrice the value for tp_order.shipping_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setShippingPrice(BigDecimal shippingPrice) {
        this.shippingPrice = shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.user_money
     *
     * @return the value of tp_order.user_money
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.user_money
     *
     * @param userMoney the value for tp_order.user_money
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.coupon_price
     *
     * @return the value of tp_order.coupon_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.coupon_price
     *
     * @param couponPrice the value for tp_order.coupon_price
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.integral
     *
     * @return the value of tp_order.integral
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.integral
     *
     * @param integral the value for tp_order.integral
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.integral_money
     *
     * @return the value of tp_order.integral_money
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getIntegralMoney() {
        return integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.integral_money
     *
     * @param integralMoney the value for tp_order.integral_money
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setIntegralMoney(BigDecimal integralMoney) {
        this.integralMoney = integralMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_amount
     *
     * @return the value of tp_order.order_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_amount
     *
     * @param orderAmount the value for tp_order.order_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.total_amount
     *
     * @return the value of tp_order.total_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.total_amount
     *
     * @param totalAmount the value for tp_order.total_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.add_time
     *
     * @return the value of tp_order.add_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Long getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.add_time
     *
     * @param addTime the value for tp_order.add_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.shipping_time
     *
     * @return the value of tp_order.shipping_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Long getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.shipping_time
     *
     * @param shippingTime the value for tp_order.shipping_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setShippingTime(Long shippingTime) {
        this.shippingTime = shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.confirm_time
     *
     * @return the value of tp_order.confirm_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Long getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.confirm_time
     *
     * @param confirmTime the value for tp_order.confirm_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setConfirmTime(Long confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.pay_time
     *
     * @return the value of tp_order.pay_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Long getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.pay_time
     *
     * @param payTime the value for tp_order.pay_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setPayTime(Long payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_prom_id
     *
     * @return the value of tp_order.order_prom_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Short getOrderPromId() {
        return orderPromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_prom_id
     *
     * @param orderPromId the value for tp_order.order_prom_id
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setOrderPromId(Short orderPromId) {
        this.orderPromId = orderPromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.order_prom_amount
     *
     * @return the value of tp_order.order_prom_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getOrderPromAmount() {
        return orderPromAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.order_prom_amount
     *
     * @param orderPromAmount the value for tp_order.order_prom_amount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setOrderPromAmount(BigDecimal orderPromAmount) {
        this.orderPromAmount = orderPromAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.discount
     *
     * @return the value of tp_order.discount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.discount
     *
     * @param discount the value for tp_order.discount
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.user_note
     *
     * @return the value of tp_order.user_note
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getUserNote() {
        return userNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.user_note
     *
     * @param userNote the value for tp_order.user_note
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setUserNote(String userNote) {
        this.userNote = userNote == null ? null : userNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.admin_note
     *
     * @return the value of tp_order.admin_note
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getAdminNote() {
        return adminNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.admin_note
     *
     * @param adminNote the value for tp_order.admin_note
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setAdminNote(String adminNote) {
        this.adminNote = adminNote == null ? null : adminNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.parent_sn
     *
     * @return the value of tp_order.parent_sn
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public String getParentSn() {
        return parentSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.parent_sn
     *
     * @param parentSn the value for tp_order.parent_sn
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setParentSn(String parentSn) {
        this.parentSn = parentSn == null ? null : parentSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.is_distribut
     *
     * @return the value of tp_order.is_distribut
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Boolean getIsDistribut() {
        return isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.is_distribut
     *
     * @param isDistribut the value for tp_order.is_distribut
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setIsDistribut(Boolean isDistribut) {
        this.isDistribut = isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.receive_time
     *
     * @return the value of tp_order.receive_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public Long getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.receive_time
     *
     * @param receiveTime the value for tp_order.receive_time
     *
     * @mbggenerated Wed Feb 28 17:18:49 CST 2018
     */
    public void setReceiveTime(Long receiveTime) {
        this.receiveTime = receiveTime;
    }

    private List<OrderGoods> orderGoodsList;

    public List<OrderGoods> getOrderGoodsList() {
        return orderGoodsList;
    }

    public void setOrderGoodsList(List<OrderGoods> orderGoodsList) {
        this.orderGoodsList = orderGoodsList;
    }
}