package cn.enjoy.mall.model;

import java.io.Serializable;

public class OrderAction implements Serializable{
    private static final long serialVersionUID = 3131238876687883450L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.action_id
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private Integer actionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.order_id
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.action_user
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private String actionUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.trade_type
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.prepay_id
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private String prepayId;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.code_url
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private String codeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.order_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.shipping_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private Integer shippingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.pay_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.action_note
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private String actionNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.log_time
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private Long logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order_action.status_desc
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    private String statusDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.action_id
     *
     * @return the value of tp_order_action.action_id
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.action_id
     *
     * @param actionId the value for tp_order_action.action_id
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.order_id
     *
     * @return the value of tp_order_action.order_id
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.order_id
     *
     * @param orderId the value for tp_order_action.order_id
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.action_user
     *
     * @return the value of tp_order_action.action_user
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public String getActionUser() {
        return actionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.action_user
     *
     * @param actionUser the value for tp_order_action.action_user
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setActionUser(String actionUser) {
        this.actionUser = actionUser == null ? null : actionUser.trim();
    }

    public String getTradeType() {
        return tradeType;
    }

    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    public String getPrepayId() {
        return prepayId;
    }

    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId;
    }

    public String getCodeUrl() {
        return codeUrl;
    }

    public void setCodeUrl(String codeUrl) {
        this.codeUrl = codeUrl;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.order_status
     *
     * @return the value of tp_order_action.order_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.order_status
     *
     * @param orderStatus the value for tp_order_action.order_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.shipping_status
     *
     * @return the value of tp_order_action.shipping_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public Integer getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.shipping_status
     *
     * @param shippingStatus the value for tp_order_action.shipping_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setShippingStatus(Integer shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.pay_status
     *
     * @return the value of tp_order_action.pay_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.pay_status
     *
     * @param payStatus the value for tp_order_action.pay_status
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.action_note
     *
     * @return the value of tp_order_action.action_note
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public String getActionNote() {
        return actionNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.action_note
     *
     * @param actionNote the value for tp_order_action.action_note
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setActionNote(String actionNote) {
        this.actionNote = actionNote == null ? null : actionNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.log_time
     *
     * @return the value of tp_order_action.log_time
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public Long getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.log_time
     *
     * @param logTime the value for tp_order_action.log_time
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setLogTime(Long logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order_action.status_desc
     *
     * @return the value of tp_order_action.status_desc
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order_action.status_desc
     *
     * @param statusDesc the value for tp_order_action.status_desc
     *
     * @mbggenerated Wed Feb 28 18:00:18 CST 2018
     */
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc == null ? null : statusDesc.trim();
    }
}