package cn.enjoy.mall.model;

import java.io.Serializable;

public class Shipping implements Serializable{
    private static final long serialVersionUID = 7981387784685348316L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_shipping.shipping_id
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    private Byte shippingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_shipping.shipping_code
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    private String shippingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_shipping.shipping_name
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    private String shippingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_shipping.shipping_desc
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    private String shippingDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_shipping.insure
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    private String insure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_shipping.enabled
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_shipping.shipping_id
     *
     * @return the value of tp_shipping.shipping_id
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public Byte getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_shipping.shipping_id
     *
     * @param shippingId the value for tp_shipping.shipping_id
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public void setShippingId(Byte shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_shipping.shipping_code
     *
     * @return the value of tp_shipping.shipping_code
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public String getShippingCode() {
        return shippingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_shipping.shipping_code
     *
     * @param shippingCode the value for tp_shipping.shipping_code
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public void setShippingCode(String shippingCode) {
        this.shippingCode = shippingCode == null ? null : shippingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_shipping.shipping_name
     *
     * @return the value of tp_shipping.shipping_name
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_shipping.shipping_name
     *
     * @param shippingName the value for tp_shipping.shipping_name
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_shipping.shipping_desc
     *
     * @return the value of tp_shipping.shipping_desc
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public String getShippingDesc() {
        return shippingDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_shipping.shipping_desc
     *
     * @param shippingDesc the value for tp_shipping.shipping_desc
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public void setShippingDesc(String shippingDesc) {
        this.shippingDesc = shippingDesc == null ? null : shippingDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_shipping.insure
     *
     * @return the value of tp_shipping.insure
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public String getInsure() {
        return insure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_shipping.insure
     *
     * @param insure the value for tp_shipping.insure
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public void setInsure(String insure) {
        this.insure = insure == null ? null : insure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_shipping.enabled
     *
     * @return the value of tp_shipping.enabled
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_shipping.enabled
     *
     * @param enabled the value for tp_shipping.enabled
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}