package cn.enjoy.mall.model;

import java.io.Serializable;

public class SpecItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_spec_item.id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_spec_item.spec_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private Integer specId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_spec_item.item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    private String item;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_spec_item.id
     *
     * @return the value of tp_spec_item.id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_spec_item.id
     *
     * @param id the value for tp_spec_item.id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_spec_item.spec_id
     *
     * @return the value of tp_spec_item.spec_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public Integer getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_spec_item.spec_id
     *
     * @param specId the value for tp_spec_item.spec_id
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setSpecId(Integer specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_spec_item.item
     *
     * @return the value of tp_spec_item.item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_spec_item.item
     *
     * @param item the value for tp_spec_item.item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }

    private boolean checked;

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }
}