package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.HotSellingGoods;
import cn.enjoy.mall.model.OrderGoods;

import java.util.List;

public interface OrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order_goods
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order_goods
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    int insert(OrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order_goods
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    int insertSelective(OrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order_goods
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    OrderGoods selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order_goods
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    int updateByPrimaryKeySelective(OrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_order_goods
     *
     * @mbggenerated Wed Feb 28 09:43:09 CST 2018
     */
    int updateByPrimaryKey(OrderGoods record);

    int insertBatch(List<OrderGoods> list);

    List<OrderGoods> selectByOrderId(Integer orderId);

    int countNotSendGoodsByOrderId(int orderId);

    List<HotSellingGoods> selectTopNSoldGoods(int n);
}