package cn.enjoy.mall.dao;


import cn.enjoy.mall.model.HotSellingGoods;

import java.util.List;

/**
 */
public interface ScheduledMapper {
    /**
     * This method was generated by MyBatis Generator.
     */
    List<HotSellingGoods> hotProduct(int count);
    /**
     * This method was generated by MyBatis Generator.
     */
    int deleteByAll();
    /**
     * This method was generated by MyBatis Generator.
     */
    int insert(HotSellingGoods hotSellingGoods);

    List<Integer> getInvalidKill();

    int disableKill(List<Integer> list);
    int cancelKillOrder(List<Integer> list);
}
