package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.Shipping;

import java.util.List;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_shipping
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    int deleteByPrimaryKey(Byte shippingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_shipping
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_shipping
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_shipping
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    Shipping selectByPrimaryKey(Byte shippingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_shipping
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_shipping
     *
     * @mbg.generated Wed Mar 21 16:54:06 CST 2018
     */
    int updateByPrimaryKey(Shipping record);

    List<Shipping> queryAll();
}