package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.UserAddress;

import java.util.List;

public interface                UserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_address
     *
     * @mbggenerated Sun Feb 25 16:24:15 CST 2018
     */
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_address
     *
     * @mbggenerated Sun Feb 25 16:24:15 CST 2018
     */
    int insert(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_address
     *
     * @mbggenerated Sun Feb 25 16:24:15 CST 2018
     */
    int insertSelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_address
     *
     * @mbggenerated Sun Feb 25 16:24:15 CST 2018
     */
    UserAddress selectByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_address
     *
     * @mbggenerated Sun Feb 25 16:24:15 CST 2018
     */
    int updateByPrimaryKeySelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_address
     *
     * @mbggenerated Sun Feb 25 16:24:15 CST 2018
     */
    int updateByPrimaryKey(UserAddress record);
    List<UserAddress> selectByUserId(String userId);
}