dfs:
  url: 192.168.0.128:8181
c3p0:
  jdbcUrl: jdbc:mysql://192.168.0.128:3303/mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  user: root
  password: root
  driverClass: com.mysql.jdbc.Driver
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false
zookeeper:
  url: zookeeper://192.168.0.128:2181 #114.115.171.119

mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  config-location: classpath:SqlMapConfig.xml
spring:
  redis:
    host: 192.168.0.128
    port: 6379
    password: 123456
  data:
    mongodb:
      uri: mongodb://192.168.0.128:27017/mall

