package cn.enjoy.users.dao;

import cn.enjoy.sys.model.Department;
import cn.enjoy.sys.model.DepartmentTree;
import cn.enjoy.sys.model.TreeViewResource;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DepartmentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	int insert(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	int insertSelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	Department selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	int updateByPrimaryKeySelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated  Thu Jun 23 09:13:11 CST 2016
	 */
	int updateByPrimaryKey(Department record);

	List<Department> loadDepartment(Department dept);

	Long maxDeptmentCode();

	Long maxLikeDeptCode(Department record);

	Long maxLengthDeptCode(Department record);

	List<Department> selectByLikeCode(String departmentCode);

	Department selectByCode(String departmentCode);

	List<Department> deptartCode(@Param("string") String string, @Param("valid") int valid);

	List<DepartmentTree> selectToTree(@Param("deptName") String deptName, @Param("parentId") String parentId);

	int isExistSameName(Department dept);

	List<Department> selectByUserId(@Param("userId") String userId);

	/**
	 * 查询用户树
	 * @return
	 * @author Ray
	 */
	List<TreeViewResource> selectUserTree();

	Department selectDepartByUserId(@Param("userId") String userId);
}