package cn.enjoy.users.dao;

import cn.enjoy.sys.model.Oauth2Client;
import org.apache.ibatis.annotations.MapKey;

import java.util.Map;

public interface Oauth2ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oauth2_client
     *
     * @mbg.generated Fri Mar 23 11:14:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oauth2_client
     *
     * @mbg.generated Fri Mar 23 11:14:21 CST 2018
     */
    int insert(Oauth2Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oauth2_client
     *
     * @mbg.generated Fri Mar 23 11:14:21 CST 2018
     */
    int insertSelective(Oauth2Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oauth2_client
     *
     * @mbg.generated Fri Mar 23 11:14:21 CST 2018
     */
    Oauth2Client selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oauth2_client
     *
     * @mbg.generated Fri Mar 23 11:14:21 CST 2018
     */
    int updateByPrimaryKeySelective(Oauth2Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oauth2_client
     *
     * @mbg.generated Fri Mar 23 11:14:21 CST 2018
     */
    int updateByPrimaryKey(Oauth2Client record);

    Oauth2Client findByClientId(String clientId);
    Oauth2Client findBySecret(String secret);

    @MapKey("clientId")
    Map<String, Oauth2Client> getAll4Map();
}