package cn.enjoy.users.dao;


import cn.enjoy.sys.model.SysDictType;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysDictTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insert(SysDictType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insertSelective(SysDictType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	SysDictType selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKeySelective(SysDictType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_type
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKey(SysDictType record);
	
	 List<SysDictType> queryAllDictType();

	List<SysDictType> queryAllDictTypePage(@Param("param") String param, PageBounds pageBounds);


	void deleteByIds(List<String> ids);
}