package cn.enjoy.users.dao;



import cn.enjoy.sys.model.SelectModel;
import cn.enjoy.sys.model.SysDictData;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysDictDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_data
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_data
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insert(SysDictData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_data
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insertSelective(SysDictData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_data
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	SysDictData selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_data
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKeySelective(SysDictData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_data
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKey(SysDictData record);
	
	  
    /**
	 * 根据TYPE查询数据字典
	 * <li>创建时间：2015年9月2日</li>
	 * <li>创建目的：【】</li>
	 * <li>修改目的：【修改人：，修改时间：】</li>
	 * @param type
	 * @return
	 */
	List<SysDictData> queryDictDataByType(String type);

	/**
	 * 根据TYPE查询数据字典
	 * <li>创建时间：2017年10月9日</li>
	 * <li>创建目的：【】</li>
	 * <li>修改目的：【修改人：，修改时间：】</li>
	 * @param code
	 * @return
	 */
	List<SysDictData> queryDictDataByCode(String code);
	
	/**
	 * 查询所有数据字典项
	 * <li>创建时间：2015年9月2日</li>
	 * <li>创建目的：【】</li>
	 * <li>修改目的：【修改人：，修改时间：】</li>
	 * @return
	 */
	List<SysDictData> queryAllDictData();
	
	/**
	 * 根据TYPE查询数据字典下拉框
	 * <li>创建人：Caiming</li>
	 * <li>创建时间：2015年9月2日</li>
	 * <li>创建目的：【】</li>
	 * <li>修改目的：【修改人：，修改时间：】</li>
	 * @param type
	 * @return
	 */
	List<SelectModel> querySelectModelByType(String type);
	
	SysDictData queryDictDataById(String id);
    /**
     * 根据字典type查询 并且 RESV1 升序排序
     * <li>创建时间：2015年9月9日</li>
     * <li>创建目的：【】</li>
     * <li>修改目的：【修改人：，修改时间：】</li>
     * @param
     *     param
     *     必须参数:
     *            type : 字典类型
     * @return
     */
    public List<SysDictData> queryDictDataByTypeAndORDER(Map param);
    
    public int insertDicData(List<SysDictData> list);
    
    /**
     *
     * @创建时间 2015年12月21日
     * @创建目的 【更加类型和中文名查字典数据】
     * @修改目的 【修改人：，修改时间：】
     * @param type
     * @return
     */
    SysDictData queryDictDataByTypeAndCode(String type, String code, String spId);
    
    SysDictData queryDataByCode(String code);
    
    SysDictData getCodeByTypeAndResv1(String RESV1);

	List<SysDictData> queryAllDictDataPage(@Param("param") String param, @Param("type") String type, PageBounds pageBounds);

	void deleteByIds(List<String> ids);
}