package cn.enjoy.users.dao;

import cn.enjoy.sys.model.SysEmployee;

public interface SysEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    int insert(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    int insertSelective(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    SysEmployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    int updateByPrimaryKeySelective(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbggenerated Mon Oct 23 14:34:04 CST 2017
     */
    int updateByPrimaryKey(SysEmployee record);

    /**
     * 根据userId查员工
     * @param userId
     * @return
     */
    SysEmployee selectByUserId(String userId);
}