package cn.enjoy.users.dao;

import cn.enjoy.sys.model.SysOrganization;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    int insert(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    int insertSelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    SysOrganization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    int updateByPrimaryKeySelective(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue May 16 11:55:39 CST 2017
     */
    int updateByPrimaryKey(SysOrganization record);

    void batchDelete(List<String> ids);

    List<SysOrganization> queryOrganizationPage(@Param("param") String param, PageBounds pageBounds);

    List<SysOrganization> queryOrganizationList();

    List<SysOrganization> queryListByUserId(@Param("userId") String userId);
}