package cn.enjoy.users.dao;

import cn.enjoy.sys.model.SelectModel;
import cn.enjoy.sys.model.SysRole;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysRoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insert(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insertSelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	SysRole selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKeySelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKey(SysRole record);


	List<SysRole> queryRoleByResourceId(Map<String, Object> map);


	List<SysRole> queryUserRoleByUserId(@Param("userId") String userId);

	SysRole selectByRoleCode(String roleCode);


	List<SelectModel> selectDefaultRole();

	List<String> selectByRoleCodeIn(@Param("roles") List<String> roles);

    void insertRole(List<SysRole> roleList);

    List<String> selectDefaultRoleName();

	List<SysRole> selectByPage(@Param("param") String param, PageBounds pageBounds);
	List<SysRole> queryRoleList();

	String selectUserIdByRoleCode(String roleCode);

	/**
	 * 查询该用户是否存在该角色
	 */
	Integer queryCountByUserIdAndRoleCode(@Param("userId") String userId, @Param("roleCode") String roleCode);
}