package cn.enjoy.users.dao;

import cn.enjoy.sys.model.MenuModel;
import cn.enjoy.sys.model.ResourceTree;
import cn.enjoy.sys.model.SysResource;
import cn.enjoy.sys.model.TreeViewResource;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysResourceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insert(SysResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int insertSelective(SysResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	SysResource selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKeySelective(SysResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbggenerated  Tue Jun 14 11:21:53 CST 2016
	 */
	int updateByPrimaryKey(SysResource record);

	List<MenuModel> queryMenus(Map<String, Object> paramMap);

	List<MenuModel> queryPermissionList(Map<String, Object> paramMap);

	List<SysResource> queryResourceByUrl(String url);

	String getIdByUrl(String url);

	String getParentIdByUrl(String url);

	List<ResourceTree> selectAddResourceTree(@Param("parentId") String parentId);

	List<TreeViewResource> selectTreeViewResource(SysResource resource);

	List<ResourceTree> selectModifyResourceTree(@Param("roleId") String roleId, @Param("parentId") String parentId);

	List<Map> queryResourceById(Map paramMap);

	PageList<SysResource> queryResourcePage(SysResource resource, PageBounds pageBounds);

	int selectChildById(String parentId);

	void lockResourceAndChild(String parentId);

	List<Map<String, Object>> selectParentName();

	void lockByPrimaryKey(String id);

	int selectParentStatusById(String id);

	void unlockResource(String id);

	List<SysResource> selectResourceList(Map<String, Object> map);

	List<MenuModel> selectOperateMenus(Map<String, Object> paramMap);

	List<SysResource> selectbyUserId(String userId);

	List<SysResource> selectbyParentId(String parentId);



	List<SysResource> sectbySysCode(String sysCode);

	/**
	 * 根据code查询resource,支付模糊匹配
	 * @创建人 Ray
	 * @创建日期 2016/11/7
	 *
	 * @param code  type of String
	 * @return List<SysResource>
	 */
	List<SysResource> selectResourceByCode(String code);
}