package cn.enjoy.users.dao;

import cn.enjoy.sys.model.SysUserBind;

public interface SysUserBindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_bind
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_bind
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    int insert(SysUserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_bind
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    int insertSelective(SysUserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_bind
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    SysUserBind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_bind
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    int updateByPrimaryKeySelective(SysUserBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_bind
     *
     * @mbggenerated Mon Oct 16 15:32:25 CST 2017
     */
    int updateByPrimaryKey(SysUserBind record);

    /**
     * 根据authId查询
     * @param authId
     * @return
     */
    SysUserBind selectByAuthId(String authId);

    /**
     * 根据email查询绑定的微信openId
     * @param email
     * @return openId
     * @author Ray
     */
    String selectOpenIdByEmail(String email);
}