package cn.enjoy.users.dao;

import cn.enjoy.sys.model.SysUser;
import cn.enjoy.sys.model.SysUserOrganization;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysUserOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_organization
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_organization
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    int insert(SysUserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_organization
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    int insertSelective(SysUserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_organization
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    SysUserOrganization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_organization
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    int updateByPrimaryKeySelective(SysUserOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_organization
     *
     * @mbggenerated Tue May 16 11:57:00 CST 2017
     */
    int updateByPrimaryKey(SysUserOrganization record);

    List<SysUserOrganization> findByOrgOrganizationId(String organizationId);

    int deleteByOrganizationIdAndUserId(@Param("organizationId") String organizationId, @Param("userId") String userId);

    SysUserOrganization selectByOrganizationIdAndUserId(@Param("organizationId") String organizationId, @Param("userId") String userId);

    SysUser findByOrgOrganizationIdAndSupervise(@Param("organizationId") String organizationId, @Param("supervise") String supervise);
}