package cn.enjoy.users.dao;

import cn.enjoy.sys.model.SysUserRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jun 15 15:17:13 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jun 15 15:17:13 CST 2016
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jun 15 15:17:13 CST 2016
     */
    int insertSelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jun 15 15:17:13 CST 2016
     */
    SysUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jun 15 15:17:13 CST 2016
     */
    int updateByPrimaryKeySelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Wed Jun 15 15:17:13 CST 2016
     */
    int updateByPrimaryKey(SysUserRole record);


    void insertUserRoleByRoleId(List<SysUserRole> list);

    void deleteUserRoleByUserId(@Param(value = "userId") String userId);

	List<SysUserRole> queryUserRoleByUserId(String userId);

    List<Map<String,Object>> queryByUserId(String userId);

    void deleteUserRoleByUserIds(Map<String, Object> record);
}