package cn.enjoy.users.dao;

import cn.enjoy.sys.model.User;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toroot_user
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toroot_user
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toroot_user
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toroot_user
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toroot_user
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toroot_user
     *
     * @mbggenerated Mon Apr 10 09:44:28 CST 2017
     */
    int updateByPrimaryKey(User record);

    User selectByUsernameAndPwd(String username, @Param("passwd") String passwd);

    List<User> quertUserByUsername(String username, PageBounds pageBounds);

    void batchDeleteUsers(Integer[] ids);
}