package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.Brand;

import java.util.List;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_brand
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_brand
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_brand
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_brand
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    Brand selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_brand
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_brand
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_brand
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKey(Brand record);

    List<Brand> selectList(Brand param);

    List<Brand> selectAll();
}