package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.GoodsAttribute;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;

import java.util.List;

public interface GoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attribute
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int deleteByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attribute
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insert(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attribute
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insertSelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attribute
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    GoodsAttribute selectByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attribute
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attribute
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attribute
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKey(GoodsAttribute record);

    /**
     * 分页查询
     * @param param
     * @param pageBounds
     * @return
     * @author Ray
     */
    PageList<GoodsAttribute> queryByPage(GoodsAttribute param, PageBounds pageBounds);

    List<GoodsAttribute> selectListByTypeId(Short typeId);
}