package cn.enjoy.mall.dao;

import cn.enjoy.mall.vo.CategoryTree;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import cn.enjoy.mall.model.GoodsCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface GoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_category
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_category
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    int insert(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_category
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    int insertSelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_category
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    GoodsCategory selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_category
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_category
     *
     * @mbggenerated Mon Feb 05 14:45:49 CST 2018
     */
    int updateByPrimaryKey(GoodsCategory record);

    List<CategoryTree> selectCategoryTree(@Param("parentId") String parentId, @Param("keywords") String keywords);
    List<CategoryTree> selectCategoryTree3(@Param("parentId") String parentId, @Param("keywords") String keywords);
    /**
     * 根据父ID查分类
     * @param parentId
     * @return
     */
    List<CategoryTree> selectCategoryByParentId(@Param("parentId") Integer parentId, @Param("isHot") Integer isHot);

    List<GoodsCategory> selectSubCategoryByParentId(@Param("parentId") Integer parentId);

    List<Map> selectGoods();

    List<GoodsCategory> selectAll();

    List<GoodsCategory> selectList(GoodsCategory param);

    List<Integer> selectIdByName(@Param("name") String name);

    PageList<GoodsCategory> queryByPage(@Param("parentId") String parentId, @Param("categoryName") String categoryName, PageBounds pageBounds);
}