package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.GoodsType;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insert(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insertSelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    GoodsType selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_type
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKey(GoodsType record);

    /**
     * 分页查询
     * @param name
     * @param pageBounds
     * @return
     * @author Ray
     */
    PageList<GoodsType> queryByPage(@Param("name") String name, PageBounds pageBounds);

    List<GoodsType> queryAll();
}