package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.GoodsAttr;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attr
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int deleteByPrimaryKey(Integer goodsAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attr
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insert(GoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attr
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insertSelective(GoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attr
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    GoodsAttr selectByPrimaryKey(Integer goodsAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attr
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attr
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(GoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_goods_attr
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKey(GoodsAttr record);

    List<GoodsAttr> selectByGoodsId(Integer goodsId);

    int deleteByGoodsId(@Param("goodsId") Integer goodsId, @Param("excludeList") List<Short> excludeList);

    int insertBatch(List<GoodsAttr> list);
}