package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.SpecItem;

import java.util.List;

public interface SpecItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insert(SpecItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int insertSelective(SpecItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    SpecItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKeySelective(SpecItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_item
     *
     * @mbggenerated Wed Feb 07 09:55:47 CST 2018
     */
    int updateByPrimaryKey(SpecItem record);

    List<SpecItem> selectListBySpecId(Integer specId);

    /**
     * 根据规格ID删除规格项
     * @param specId
     */
    void deleteBySpecId(int specId);

}