package cn.enjoy.mall.dao;

import cn.enjoy.mall.model.SpecGoodsPrice;
import cn.enjoy.mall.vo.GoodsSpecPriceDetailVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SpecGoodsPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_goods_price
     *
     * @mbggenerated Thu Feb 08 09:55:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_goods_price
     *
     * @mbggenerated Thu Feb 08 09:55:14 CST 2018
     */
    int insert(SpecGoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_goods_price
     *
     * @mbggenerated Thu Feb 08 09:55:14 CST 2018
     */
    int insertSelective(SpecGoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_goods_price
     *
     * @mbggenerated Thu Feb 08 09:55:14 CST 2018
     */
    SpecGoodsPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_goods_price
     *
     * @mbggenerated Thu Feb 08 09:55:14 CST 2018
     */
    int updateByPrimaryKeySelective(SpecGoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_goods_price
     *
     * @mbggenerated Thu Feb 08 09:55:14 CST 2018
     */
    int updateByPrimaryKey(SpecGoodsPrice record);

    List<SpecGoodsPrice> selectByGoodsId(Integer goodsId);

    Integer selectDefaultIdByGoodsId(Integer goodsId);

    int deleteByGoodsId(@Param("goodsId") Integer goodsId, @Param("excludeList") List<Integer> excludeList);

    int insertBatch(List<SpecGoodsPrice> list);

    GoodsSpecPriceDetailVo selectDetailById(Integer id);
}